// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqk2JqialK2A8ERCEJh1DOi3Nx3rZMRvk',
    appId: '1:407532823225:android:bc4f415b93ad1de8f37168',
    messagingSenderId: '407532823225',
    projectId: 'fcm-projects-c4128',
    databaseURL: 'https://fcm-projects-c4128-default-rtdb.firebaseio.com',
    storageBucket: 'fcm-projects-c4128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNBESbFQC-roegbSx74STpszoJ58E6jE',
    appId: '1:407532823225:ios:55e88cd52020ce9bf37168',
    messagingSenderId: '407532823225',
    projectId: 'fcm-projects-c4128',
    databaseURL: 'https://fcm-projects-c4128-default-rtdb.firebaseio.com',
    storageBucket: 'fcm-projects-c4128.appspot.com',
    iosBundleId: 'com.example.foodDeleveryApp',
  );
}
